INSERT INTO public.states(name, abbr, slug, created_at, updated_at) VALUES
                                                                        ('Acre', 'AC', 'acre', now(), now()),
                                                                        ('Alagoas', 'AL', 'alagoas', now(), now()),
                                                                        ('Amazonas', 'AM', 'amazonas', now(), now()),
                                                                        ('Amapá', 'AP', 'amapa', now(), now()),
                                                                        ('Bahia', 'BA', 'bahia', now(), now()),
                                                                        ('Ceará', 'CE', 'ceara', now(), now()),
                                                                        ('Distrito Federal', 'DF', 'distrito-federal', now(), now()),
                                                                        ('Espírito Santo', 'ES', 'espirito-santo', now(), now()),
                                                                        ('Goiás', 'GO', 'goiás', now(), now()),
                                                                        ('Maranhão', 'MA', 'maranhao', now(), now()),
                                                                        ('Minas Gerais', 'MG', 'minas-gerais', now(), now()),
                                                                        ('Mato Grosso do Sul', 'MS', 'mato-grosso-do-sul', now(), now()),
                                                                        ('Mato Grosso', 'MT', 'mato-grosso', now(), now()),
                                                                        ('Pará', 'PA', 'para', now(), now()),
                                                                        ('Paraíba', 'PB', 'paraiba', now(), now()),
                                                                        ('Pernambuco', 'PE', 'pernambuco', now(), now()),
                                                                        ('Piauí', 'PI', 'piaui', now(), now()),
                                                                        ('Paraná', 'PR', 'parana', now(), now()),
                                                                        ('Rio de Janeiro', 'RJ', 'rio-de-janeiro', now(), now()),
                                                                        ('Rio Grande do Norte', 'RN', 'rio-grande-do-norte', now(), now()),
                                                                        ('Rondônia', 'RO', 'rondonia', now(), now()),
                                                                        ('Roraima', 'RR', 'roraima', now(), now()),
                                                                        ('Rio Grande do Sul', 'RS', 'rio-grande-do-sul', now(), now()),
                                                                        ('Santa Catarina', 'SC', 'santa-catarina', now(), now()),
                                                                        ('Sergipe', 'SE', 'sergipe', now(), now()),
                                                                        ('São Paulo', 'SP', 'sao-paulo', now(), now()),
                                                                        ('Tocantins', 'TO', 'tocantins', now(), now());
