; opcache.ini
; Configuração do OPcache para otimização de performance do PHP.

opcache.enable=1
opcache.enable_cli=0 ; Desabilita OPcache para CLI para evitar problemas em scripts curtos
opcache.memory_consumption=128 ; Quantidade de memória em MB que o OPcache pode usar
opcache.interned_strings_buffer=8 ; Tamanho do buffer para strings internas em MB
opcache.max_accelerated_files=10000 ; Número máximo de arquivos PHP para armazenar em cache
opcache.revalidate_freq=0 ; Frequência de revalidação de arquivos (0 para sempre revalidar, ideal em produção com deploy controlado)
opcache.validate_timestamps=0 ; Desabilita a validação de timestamps (ideal para produção, requer reload manual do PHP-FPM após deploy)
opcache.dups_fix=1 ; Necessário para alguns frameworks
opcache.consistency_checks=0 ; Desabilita verificações de consistência (para performance)
opcache.fast_shutdown=1 ; Habilita desligamento rápido para melhor performance
