; Ativa o OPcache
opcache.enable=1

; Valida a integridade do cache
opcache.validate_timestamps=1

; Tempo em segundos para a validação do cache (0 para sempre revalidar)
opcache.revalidate_freq=0

; O tamanho da memória compartilhada em megabytes
opcache.memory_consumption=128

; O número máximo de arquivos em cache
opcache.max_accelerated_files=10000

; Adiciona uma 'string' chave para o cache
opcache.interned_strings_buffer=8

; Opção para habilitar ou desabilitar o cache para scripts com comentários
opcache.save_comments=1

; Habilita otimizações adicionais
opcache.enable_file_override=1

; Desativa a depuração
opcache.optimization_level=0x7FFF
